import rslcurl;
import curl_const;

var r;
var url = "https://data.nalog.ru/css/ul2018/img/logo.svg";
var s;


PrintLn(CurlVersion());

var h = CurlEasyInit();
PrintLn(h);
//r = CurlEasySetOptStr(h,CURLOPT_URL,url);
r = CurlEasySetOpt(h, CURLOPT_URL, url);
PrintLn("CurlEasySetOpt: ", r);

r = CurlEasySetWriteFile(h, "logo.svg");
PrintLn("CurlEasySetWrite: ", r);

r = CurlEasyPerform(h);
PrintLn("CurlEasyPerform: ", r);

s = CurlEasyGetHeader(h, "Content-Type");
PrintLn("Content-Type: ", s);

r = CurlEasyGetInfo(h, CURLINFO_RESPONSE_CODE);
PrintLn("CurlEasyGetInfo response_code: ", r);

r = CurlEasyGetInfo(h, CURLINFO_SIZE_DOWNLOAD_T);
PrintLn("CurlEasyGetInfo download size: ", r);


r = CurlEasyCleanup(h);
PrintLn("CurlEasyСleanup: ", r);
