import rslcurl;
import curl_const;

var r;
var url = "https://data.nalog.ru/css/ul2018/img/logo.svg";
var s;
var n;

// PrintLn(CurlVersion());

var h = CurlEasyInit();
PrintLn(h);
r = CurlEasySetOptStr(h, CURLOPT_URL, url);
PrintLn("CurlEasySetOptStr: ", r);

r = CurlEasySetWriteString(h);
PrintLn("CurlEasySetWriteString: ", r);

r = CurlEasyPerform(h);
PrintLn("CurlEasyPerform: ", r);

s = CurlGetString();
PrintLn("CurlGetString: ", s);


r = CurlEasyCleanup(h);
PrintLn("CurlEasyCleanup: ", r);


